### ISSUE TITLE
Compilation Fail!!!

### ISSUE THREAD

**Issue by Gary-oak-Star** [TeamVoss/VossII#20]
I ran `make -C src install_all` as the README said. However, even though I followed the instructions in README, and install all the dependencies binary, I still cannot compile this project from source code, the error showed like:

```
cc -g -DDEBUG  -D__STDC_LIMIT_MACROS -D __STDC_FORMAT_MACROS -Wall -Wextra -Werror -DVERSION_DATE='"23/07/24"' -DDEFAULT_PLUGIN_DIR='"/xxx/VossII/vosslib"' -DFL_BINARY=1 -std=gnu99 -I../../include -I/xxx/VossII/src/external/minisat/include -I/usr/include/tcl8.6/ -DROOT_DIR='"/xxx/VossII"' -c new_bdd.c
In file included from fl.h:66,
                 from new_bdd.h:100,
                 from new_bdd.c:11:
./strings.h:75:2: error: unknown type name ‘range_ptr’
   75 |  range_ptr      next;
      |  ^~~~~~~~~
./strings.h:79:9: error: unknown type name ‘string’
   79 |         string     name;
      |         ^~~~~~
./strings.h:80:9: error: unknown type name ‘range_ptr’
   80 |         range_ptr  ranges;
      |         ^~~~~~~~~
./strings.h:86:5: error: unknown type name ‘vec_ptr’
   86 |     vec_ptr  next;
      |     ^~~~~~~
./strings.h:90:5: error: unknown type name ‘vec_ptr’
   90 |     vec_ptr      vec;
      |     ^~~~~~~
./strings.h:91:5: error: unknown type name ‘vec_list_ptr’
   91 |     vec_list_ptr next;
      |     ^~~~~~~~~~~~
./strings.h:95:5: error: unknown type name ‘string’
   95 |     string         name;
      |     ^~~~~~
./strings.h:96:5: error: unknown type name ‘sname_list_ptr’
   96 |     sname_list_ptr next;
      |     ^~~~~~~~~~~~~~
./strings.h:100:5: error: unknown type name ‘vec_ptr’
  100 |     vec_ptr        vec;
      |     ^~~~~~~
./strings.h:101:5: error: unknown type name ‘string’
  101 |     string         name_signature;
      |     ^~~~~~
./strings.h:102:5: error: unknown type name ‘merge_list_ptr’
  102 |     merge_list_ptr prev;
      |     ^~~~~~~~~~~~~~
./strings.h:103:5: error: unknown type name ‘merge_list_ptr’
  103 |     merge_list_ptr next;
      |     ^~~~~~~~~~~~~~
./strings.h:107:2: error: unknown type name ‘ustr_mgr’
  107 |  ustr_mgr    ustring_mgr;
      |  ^~~~~~~~
./strings.h:108:2: error: unknown type name ‘rec_mgr’
  108 |  rec_mgr     vec_rec_mgr;     // TYPE: vec_rec
      |  ^~~~~~~
./strings.h:109:2: error: unknown type name ‘rec_mgr’
  109 |  rec_mgr     range_rec_mgr;     // TYPE: range_rec
      |  ^~~~~~~
./strings.h:110:2: error: unknown type name ‘rec_mgr’
  110 |  rec_mgr     vec_list_rec_mgr;     // TYPE: vec_list_rec
      |  ^~~~~~~
./strings.h:111:2: error: unknown type name ‘hash_record’
  111 |  hash_record sig2vec_list;     // TYPE: string -> vec_list_ptr
      |  ^~~~~~~~~~~
make[1]: *** [Makefile:47: new_bdd.o] Error 1
make[1]: Leaving directory '/xxx/VossII/src/bin/fl'
make: *** [Makefile:131: fl] Error 2
make: Leaving directory '/xxx/VossII/src
```

The environment I used:
* gcc version : 9.4.0
* os/hardware:
<img width="484" alt="image" src="https://github.com/TeamVoss/VossII/assets/120406793/43afd54c-75cd-4295-87fd-5475193dcf0b">

**Comment by ElizabethSotomayor** [comment]
I am having the same issue. Did you ever figure out the cause?

**Comment by Gary-oak-Star** [comment]
> I am having the same issue. Did you ever figure out the cause?

Not yet. Have you fixed it?

**Comment by tianrui-wei** [comment]
Could you check the following things

1. Are the dependency in [README](https://github.com/TeamVoss/VossII#building-on-ubuntudebian) correctly installed?
2. Can you show me the gcc/g++ version by executing `cc --version` and `c++ --version` in your terminal?

**Comment by Gy-Hu-Star** [comment]
1. Sure, oss-cad-suite has been installed (PATH also has been export)
2. Here's the return info
<img width="687" alt="image" src="https://github.com/TeamVoss/VossII/assets/120406793/7b367024-6039-4ce7-bc3b-60966b82367c">

**Comment by Gary-oak-Star** [comment]
> Could you check the following things
> 
> 1. Are the dependency in [README](https://github.com/TeamVoss/VossII#building-on-ubuntudebian) correctly installed?
> 2. Can you show me the gcc/g++ version by executing `cc --version` and `c++ --version` in your terminal?



1. Sure, oss-cad-suite has been installed (PATH also has been export)
2. Here's the return info
<img width="687" alt="image" src="https://github.com/TeamVoss/VossII/assets/120406793/7b367024-6039-4ce7-bc3b-60966b82367c">

**Comment by cjhseger** [comment]
For some reason it looks like that gcc is not picking up the standard library strings.h but the local strings.h, even though fl.h says #include <strings.h>.

To avoid the problem, I've renamed the local strings.h voss_strings.h.
If you pull this version, see if it solves the problem.

 --- Carl

**Comment by ElizabethSotomayor** [comment]
Hello, what fixed this issue for me was downloading the prebuilt binary package instead and adding ./voss/bin to my path, along with the ./oss-cad-suite/bin tool.

**Comment by Gary-oak-Star** [comment]
> For some reason it looks like that gcc is not picking up the standard library strings.h but the local strings.h, even though fl.h says #include <strings.h>.
> 
> To avoid the problem, I've renamed the local strings.h voss_strings.h. If you pull this version, see if it solves the problem.
> 
> --- Carl

Thanks! Problem solved
