### ISSUE TITLE
programmatically parse or generate fl?

### ISSUE THREAD

**Issue by mfernan2** [TeamVoss/VossII#7]
Is there any planned support for writing your own standalone programs for parsing or generating fl? For the first case, I'm picturing a library that encapsulates Voss' lexer and parser that you can link against and call, and then some support for walking the resulting abstract syntax tree (AST). For the second case, I'm picturing support for programmatically constructing an fl AST that can be easily serialized to a string/file.

I don't know whether either of these are on the road map and I didn't immediately see anything hinting this in the user guide. But I'm thinking about some aspirational use cases of importing/exporting to/from Voss from other systems.

**Comment by cjhseger** [comment]
Nice idea, but I'm afraid it's not on the roadmap for the foreseeable future. 
(It could happen when I get annoyed enough to clean up the parser :-))
